### ISSUE TITLE
Verificação de versão e apache

### ISSUE THREAD

**Issue by YoungTalita** [kazankay/UnimepEngSw004#3]
[verificacao.de.versao.e.apache.docx](https://github.com/kazankay/UnimepEngSw004/files/1883974/verificacao.de.versao.e.apache.docx)

**Comment by kazankay** [comment]
Valeu

**Comment by kazankay** [comment]
![6](https://user-images.githubusercontent.com/37197065/38553968-54e24b9c-3c97-11e8-96d2-6a27026a8423.png)
![7](https://user-images.githubusercontent.com/37197065/38553969-55042f28-3c97-11e8-8c5e-a277f581adc6.png)
![8](https://user-images.githubusercontent.com/37197065/38553970-5523a3da-3c97-11e8-83f9-3fd2b96a60ad.png)
![9](https://user-images.githubusercontent.com/37197065/38553971-55447786-3c97-11e8-958e-4f944ffc49d9.png)
![10](https://user-images.githubusercontent.com/37197065/38553972-557efd7a-3c97-11e8-8649-2ea586bbfae9.png)
![1](https://user-images.githubusercontent.com/37197065/38553973-55a16892-3c97-11e8-85ed-fbec7e4a2574.png)
![2](https://user-images.githubusercontent.com/37197065/38553975-55c576ba-3c97-11e8-8835-cd67d38c6506.png)
![3](https://user-images.githubusercontent.com/37197065/38553976-55e38bfa-3c97-11e8-9d5c-a9910f49e95b.png)
![4](https://user-images.githubusercontent.com/37197065/38553977-56021a8e-3c97-11e8-969d-2894a3b9d579.png)
![5](https://user-images.githubusercontent.com/37197065/38553979-5620e2a2-3c97-11e8-9839-2b8a83eb26c6.png)
